[package]
name = "krux-fuzz"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking"] }

[[bin]]
name = "prepare-fuzz"
path = "src/main.rs"
test = false
doc = false
bench = false

