[package]
name = "krux-fuzz"
version = "0.1.0"
edition = "2024"

[dependencies]
prepare_krux_env = { path = "crates/prepare_krux_env" }

[[bin]]
name = "prepare-fuzz"
path = "src/main.rs"
test = false
doc = false
bench = false
